{
{-
This file represents the HaCoTeB parser. DON'T CHANGE IT, it is
autogenerated from Parser.x using alex. See Makefile or that file for details.
-}
module HaCoTeB.Parser where
}

%wrapper "posn"

$digit = 0-9
$alpha = [a-zA-Z]
$alphanum = [a-zA-Z0-9]
